sudo: false
language: node_js
node_js:
  - "iojs"
cache:
  directories:
    - node_modules
before_install:
  - npm i -g npm@^4.0.0
before_script:
  - npm prune
script:
  - npm run test:single
  - npm run check-coverage
#after_sucess:
